### ISSUE TITLE
Errors running Dxy, Tajima's D and Watterson's

### ISSUE THREAD

**Issue by cgrootcrego** [ksamuk/pixy#143]
Just want to say, I really like this tool and am excited to use the new features :D

**Describe the bug**
Using version 2.0.0.beta2, I only get pi to work. I get errors for Dxy, tajima and watterson. I am using a VCF and BED file that worked without problems on version 1.2.5.beta1 for pi and Dxy.

**A reproducible example of the bug**
Please include the following so we can debug the issue:
(1) The full command you used to run pixy, including all arguments

pixy --stats dxy --vcf Merged.Monomorphic.BiAllelicVariantSites.pass.ANNOTATED.edited.vcf.gz --populations popfile.txt --output_prefix Brom1776_Tlei_All_Selected_genes --output_folder 4_NucleotideDiversity --bed_file Brom1776_Tlei_All_Selected_genes.sorted.bed

Output:
````
2025-04-18 15:41:42,781 pixy.__main__:main:273 [INFO]: [pixy] pixy 2.0.0.beta2
2025-04-18 15:41:42,781 pixy.__main__:main:274 [INFO]: [pixy] See documentation at https://pixy.readthedocs.io/en/latest/
2025-04-18 15:41:42,818 pixy.args_validation:check_and_validate_args:477 [INFO]: Validating VCF and input parameters...
2025-04-18 15:41:42,818 pixy.args_validation:check_and_validate_args:480 [INFO]: Checking write access...
2025-04-18 15:41:42,818 pixy.args_validation:check_and_validate_args:487 [INFO]: Checking CPU configuration...
2025-04-18 15:41:42,822 pixy.args_validation:check_and_validate_args:510 [INFO]: Checking for invariant sites...
2025-04-18 15:41:45,420 pixy.args_validation:check_and_validate_args:547 [INFO]: Checking chromosome data...
2025-04-18 15:41:45,428 pixy.args_validation:check_and_validate_args:555 [INFO]: Checking intervals/sites...
2025-04-18 15:41:45,428 pixy.args_validation:check_and_validate_args:577 [WARNING]: The following chromosomes are in the BED file but do not occur in the VCF and will be ignored: ['Tlei_chr16', 'Tlei_chr3', 'Tlei_chr4', 'Tlei_chr10', 'Tlei_chr13', 'Tlei_chr21', 'Tlei_chr19', 'Tlei_chr24', 'Tlei_chr5', 'Tlei_chr20', 'Tlei_chr22', 'Tlei_chr26', 'Tlei_chr17', 'Tlei_chr7', 'Tlei_chr11', 'Tlei_chr18', 'Tlei_chr8', 'Tlei_chr15', 'Tlei_chr6', 'Tlei_chr12', 'Tlei_chr9', 'Tlei_chr23', 'Tlei_chr25', 'Tlei_chr14']
2025-04-18 15:41:45,429 pixy.args_validation:check_and_validate_args:605 [INFO]: Checking sample data...
2025-04-18 15:41:45,444 pixy.args_validation:check_and_validate_args:647 [INFO]: All initial checks passed!
2025-04-18 15:41:45,458 pixy.__main__:main:284 [INFO]: [pixy] Preparing for calculation of summary statistics: dxy
2025-04-18 15:41:45,458 pixy.__main__:main:296 [INFO]: [pixy] Data set contains 33 populations, 2 chromosome(s), and 202 sample(s)
2025-04-18 15:41:45,458 pixy.__main__:main:306 [INFO]: [pixy] Windows sourced from: Brom1776_Tlei_All_Selected_genes.sorted.bed
2025-04-18 15:41:45,458 pixy.__main__:main:313 [INFO]: Started calculations at         15:41:45 on 2025-04-18
2025-04-18 15:41:45,458 pixy.__main__:main:317 [INFO]: [pixy] Using 1 out of 32 available CPU cores
2025-04-18 15:41:45,458 pixy.__main__:main:365 [INFO]: [pixy] Processing chromosome/contig Tlei_chr1
IndexError: index 1 is out of bounds for axis 1 with size 1
````

pixy --stats tajima_d --vcf Merged.Monomorphic.BiAllelicVariantSites.pass.ANNOTATED.edited.vcf.gz --populations popfile.txt --output_prefix Brom1776_Tlei_All_Selected_genes --output_folder 4_NucleotideDiversity --bed_file Brom1776_Tlei_All_Selected_genes.sorted.bed

Output:
````
2025-04-18 15:43:21,213 pixy.__main__:main:273 [INFO]: [pixy] pixy 2.0.0.beta2
2025-04-18 15:43:21,213 pixy.__main__:main:274 [INFO]: [pixy] See documentation at https://pixy.readthedocs.io/en/latest/
2025-04-18 15:43:21,241 pixy.args_validation:check_and_validate_args:477 [INFO]: Validating VCF and input parameters...
2025-04-18 15:43:21,241 pixy.args_validation:check_and_validate_args:480 [INFO]: Checking write access...
2025-04-18 15:43:21,242 pixy.args_validation:check_and_validate_args:487 [INFO]: Checking CPU configuration...
2025-04-18 15:43:21,244 pixy.args_validation:check_and_validate_args:510 [INFO]: Checking for invariant sites...
2025-04-18 15:43:23,878 pixy.args_validation:check_and_validate_args:547 [INFO]: Checking chromosome data...
2025-04-18 15:43:23,885 pixy.args_validation:check_and_validate_args:555 [INFO]: Checking intervals/sites...
2025-04-18 15:43:23,886 pixy.args_validation:check_and_validate_args:577 [WARNING]: The following chromosomes are in the BED file but do not occur in the VCF and will be ignored: ['Tlei_chr18', 'Tlei_chr12', 'Tlei_chr4', 'Tlei_chr25', 'Tlei_chr7', 'Tlei_chr24', 'Tlei_chr16', 'Tlei_chr19', 'Tlei_chr5', 'Tlei_chr11', 'Tlei_chr21', 'Tlei_chr20', 'Tlei_chr3', 'Tlei_chr26', 'Tlei_chr14', 'Tlei_chr23', 'Tlei_chr13', 'Tlei_chr6', 'Tlei_chr15', 'Tlei_chr8', 'Tlei_chr17', 'Tlei_chr22', 'Tlei_chr10', 'Tlei_chr9']
2025-04-18 15:43:23,886 pixy.args_validation:check_and_validate_args:605 [INFO]: Checking sample data...
2025-04-18 15:43:23,900 pixy.args_validation:check_and_validate_args:647 [INFO]: All initial checks passed!
2025-04-18 15:43:23,913 pixy.__main__:main:284 [INFO]: [pixy] Preparing for calculation of summary statistics: tajima_d
2025-04-18 15:43:23,913 pixy.__main__:main:296 [INFO]: [pixy] Data set contains 33 populations, 2 chromosome(s), and 202 sample(s)
2025-04-18 15:43:23,913 pixy.__main__:main:306 [INFO]: [pixy] Windows sourced from: Brom1776_Tlei_All_Selected_genes.sorted.bed
2025-04-18 15:43:23,913 pixy.__main__:main:313 [INFO]: Started calculations at         15:43:23 on 2025-04-18
2025-04-18 15:43:23,913 pixy.__main__:main:317 [INFO]: [pixy] Using 1 out of 32 available CPU cores
2025-04-18 15:43:23,913 pixy.__main__:main:365 [INFO]: [pixy] Processing chromosome/contig Tlei_chr1
AssertionError: gt_region is None
````

pixy --stats watterson_theta --vcf Merged.Monomorphic.BiAllelicVariantSites.pass.ANNOTATED.edited.vcf.gz --populations popfile.txt --output_prefix Brom1776_Tlei_All_Selected_genes --output_folder 4_NucleotideDiversity --bed_file Brom1776_Tlei_All_Selected_genes.sorted.bed

Output:
````
2025-04-18 15:44:39,655 pixy.__main__:main:273 [INFO]: [pixy] pixy 2.0.0.beta2
2025-04-18 15:44:39,655 pixy.__main__:main:274 [INFO]: [pixy] See documentation at https://pixy.readthedocs.io/en/latest/
2025-04-18 15:44:39,681 pixy.args_validation:check_and_validate_args:477 [INFO]: Validating VCF and input parameters...
2025-04-18 15:44:39,681 pixy.args_validation:check_and_validate_args:480 [INFO]: Checking write access...
2025-04-18 15:44:39,681 pixy.args_validation:check_and_validate_args:487 [INFO]: Checking CPU configuration...
2025-04-18 15:44:39,685 pixy.args_validation:check_and_validate_args:510 [INFO]: Checking for invariant sites...
2025-04-18 15:44:42,312 pixy.args_validation:check_and_validate_args:547 [INFO]: Checking chromosome data...
2025-04-18 15:44:42,320 pixy.args_validation:check_and_validate_args:555 [INFO]: Checking intervals/sites...
2025-04-18 15:44:42,321 pixy.args_validation:check_and_validate_args:577 [WARNING]: The following chromosomes are in the BED file but do not occur in the VCF and will be ignored: ['Tlei_chr13', 'Tlei_chr5', 'Tlei_chr26', 'Tlei_chr3', 'Tlei_chr20', 'Tlei_chr22', 'Tlei_chr12', 'Tlei_chr11', 'Tlei_chr9', 'Tlei_chr14', 'Tlei_chr21', 'Tlei_chr25', 'Tlei_chr18', 'Tlei_chr10', 'Tlei_chr8', 'Tlei_chr4', 'Tlei_chr19', 'Tlei_chr7', 'Tlei_chr23', 'Tlei_chr6', 'Tlei_chr24', 'Tlei_chr17', 'Tlei_chr16', 'Tlei_chr15']
2025-04-18 15:44:42,321 pixy.args_validation:check_and_validate_args:605 [INFO]: Checking sample data...
2025-04-18 15:44:42,337 pixy.args_validation:check_and_validate_args:647 [INFO]: All initial checks passed!
2025-04-18 15:44:42,349 pixy.__main__:main:284 [INFO]: [pixy] Preparing for calculation of summary statistics: watterson_theta
2025-04-18 15:44:42,349 pixy.__main__:main:296 [INFO]: [pixy] Data set contains 33 populations, 2 chromosome(s), and 202 sample(s)
2025-04-18 15:44:42,349 pixy.__main__:main:306 [INFO]: [pixy] Windows sourced from: Brom1776_Tlei_All_Selected_genes.sorted.bed
2025-04-18 15:44:42,349 pixy.__main__:main:313 [INFO]: Started calculations at         15:44:42 on 2025-04-18
2025-04-18 15:44:42,349 pixy.__main__:main:317 [INFO]: [pixy] Using 1 out of 32 available CPU cores
2025-04-18 15:44:42,349 pixy.__main__:main:365 [INFO]: [pixy] Processing chromosome/contig Tlei_chr1
AssertionError: genotype array is None
````

(2) A subset of your VCF (the smallest subset needed to demonstrate the problem) 
Can't manage a file small enough for upload through GitHub, sorry 

(3) The full populations file
(4) Any other files needed to reproduce the problem (sites, bed file, etc.)

**OS information**
Linux

**Comment by cgrootcrego** [comment]
[subsampled_10K.vcf.gz](https://github.com/user-attachments/files/19813160/subsampled_10K.vcf.gz)

[popfile.txt](https://github.com/user-attachments/files/19813161/popfile.txt)

**Comment by cgrootcrego** [comment]
It also appears that --output_folder is a required argument now. When I leave it out I get: OSError: The output folder  is not writable

**Comment by ksamuk** [comment]
Can you include your .bed file as well please?

**Comment by cgrootcrego** [comment]
[BEDfile.txt](https://github.com/user-attachments/files/19831201/BEDfile.txt)

**Comment by Winsher** [comment]
Hi! i have a same mistake:
multiprocess.pool.RemoteTraceback:
"""
AssertionError: genotype array is None
"""

The above exception was the direct cause of the following exception:

AssertionError: genotype array is None

i use the same vcf.gz ,but the 2.0.0 can't run and the old version can do it.

**Comment by wushyer** [comment]
I have the same error with 'IndexError: index 1 is out of bounds for axis 1 with size 1'.

**Comment by periperipatus** [comment]
Hello, I am getting the same issues, on a dataset ([link](https://buckeyemailosu-my.sharepoint.com/:u:/g/personal/bolton_161_osu_edu/EUYcvjYLQXhBlMvwHr5EPO8BQaz091mJI5Ai92Tkd8PkXQ?e=u8rK2N)) that I have been previously able to run dxy,pi and fst on. 

here is the command running version 2.0.0.beta4:

```
pixy --stats pi dxy fst \ ## also fails when including watterson and tajima
--vcf $VCF --n_cores 4 \
--populations $poplist --window_size 10000 \ 
--include_multiallelic_snps \ ## also tried without this parameter and same error
--output_folder ../../diversity/pixy_v2 --output_prefix pixy.${chrom}.10kb
```

below is the error:


```
multiprocess.pool.RemoteTraceback: 
"""
Traceback (most recent call last):
  File "/Users/bolton.161/miniforge3/envs/pixy/lib/python3.11/site-packages/multiprocess/pool.py", line 125, in worker
    result = (True, func(*args, **kwds))
                    ^^^^^^^^^^^^^^^^^^^
  File "/Users/bolton.161/miniforge3/envs/pixy/lib/python3.11/site-packages/pixy/core.py", line 436, in compute_summary_stats
    assert gt_array is not None, "genotype array is None"
           ^^^^^^^^^^^^^^^^^^^^
AssertionError: genotype array is None
"""

The above exception was the direct cause of the following exception:

AssertionError: genotype array is None
```

**Comment by ksamuk** [comment]
Hi all, this should be fixed in the latest version, 2.0.0.beta5, which is on conda-forge now. Let me know if it works!

**Comment by wushyer** [comment]
> I have the same error with 'IndexError: index 1 is out of bounds for axis 1 with size 1'.

This error is fixed now and I don't have other errors. Thanks man.

**Comment by ksamuk** [comment]
@wushyer, great, you're welcome! @Winsher looks like you are having a different problem, can you open a new issue and follow the instructions there? Thanks!

**Comment by Winsher** [comment]
ok sure

> [@wushyer](https://github.com/wushyer), great, you're welcome! [@Winsher](https://github.com/Winsher) looks like you are having a different problem, can you open a new issue and follow the instructions there? Thanks!

**Comment by cgrootcrego** [comment]
Hi there, using the same files I sent here, the dxy run is working, but I still get the same errors for tajima_d and watterson_theta as before.

**Comment by ksamuk** [comment]
Can you post the new error you are getting? Is it same message (IndexError: index 1 is out of bounds for axis 1 with size 1) or the one that @Winsher reported?

**Comment by cgrootcrego** [comment]
It seems to be the same that Winsher posted, but I also already posted these errors in my initial message above. Should I migrate that to a new issue / winshers issue?

**Comment by ksamuk** [comment]
OK great thanks, and no need, I will post the new fix over there shortly! The dxy issue seems to now be resolved, so I'll close this issue for now.
